language: cpp
sudo: required
dist: precise

matrix:
  include:
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
            - george-edison55-precise-backports
          packages:
            - clang-3.6
            - cmake
            - cmake-data
      env: COMPILER=clang++-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
            - george-edison55-precise-backports
          packages:
            - clang-3.7
            - cmake
            - cmake-data
      env: COMPILER=clang++-3.7
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
            - george-edison55-precise-backports
          packages:
            - clang-3.8
            - cmake
            - cmake-data
      env: COMPILER=clang++-3.8

script:
  - mkdir Release
  - mkdir Debug
  - cd Release
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=$COMPILER ..
  - make
  - cd ..
  - cd Debug
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=$COMPILER ..
  - make
  - ./bin/run_tests
  - cd ../Release
  - ./bin/run_tests